### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by johntaxmi** [disease-sh/node-api#51]
How can i make it check if the second argument after the command is an valid country?
like !covid sdfsdfsdfsdf
checks if `sdfsdfsdfsdf` is a valid country.
Coz when its not the message embed is all "undefined"

**Comment by puf17640** [comment]
Are you confusing this with the [covid-bot](https://github.com/puf17640/covid-bot) repository?

**Comment by johntaxmi** [comment]
Nope am using     "novelcovid": "^3.0.0"

**Comment by puf17640** [comment]
So why are you referring to a command like `!covid ...` instead of talking code? 

I'm currently not on my laptop but just try querying whatever 'country' you have, if it does not exist, it should return something different than normally

**Comment by johntaxmi** [comment]
And how can i make it check if the country argument is a valid country or not?

**Comment by puf17640** [comment]
you can get a list of countries from the API repository (should be in ./ called countries.json) and then check in your code

**Comment by puf17640** [comment]
here it is: https://github.com/disease-sh/API/blob/master/utils/countries.js

**Comment by johntaxmi** [comment]
I made something like that 
` const countrycovid = args[1]
    const countrydata = await api.countries({ country: countrycovid })
if(countrydata == null) return message.channel.send("Δεν ήταν δυνατή η εύρεση δεδομένων για αυτήν τη χώρα");`

but it doesnt work. I will try your way now.

**Comment by JustinCLT** [comment]
I made something like this
`const argscovid = args[1]
 const countrydata = await covid.countries({country: argscovid});
 if (!countrydata.cases){
        message.reply('Country Invalid!')
    } else {
  (your covid19 stats)`

And it worked for me

**Comment by JustinCLT** [comment]
I made something like this
`const argscovid = args[1]`
`const countrydata = await covid.countries({country: argscovid}); `
`if (!countrydata.cases){`
`message.reply('Country Invalid!') `
`} else { `
`(your covid19 stats)`

And it worked for me
