### ISSUE TITLE
Wrong type declaration

### ISSUE THREAD

**Issue by Kayxue** [disease-sh/node-api#64]
![Untitled](https://user-images.githubusercontent.com/26020165/118596654-3da86180-b7de-11eb-8650-c5d3b9376807.png)

Should be
![Untitled](https://user-images.githubusercontent.com/26020165/118596776-63ce0180-b7de-11eb-8e60-94f53be7f902.png)

**Comment by puf17640** [comment]
feel free to open a PR :)
